---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "module-facilities-api-config"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "module-facilities-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.module_facilities_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.module_facilities_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.module_facilities_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.module_facilities_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.module_facilities_api.HTTP_PORTS }}"
  CACHE_HOST: "{{ .Values.config.module_facilities_api.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.module_facilities_api.CACHE_PORT }}"
  VELOTIMEDB_HOST: "{{ .Values.config.module_facilities_api.VELOTIMEDB_HOST }}"
  VELOTIMEDB_PORT: "{{ .Values.config.module_facilities_api.VELOTIMEDB_PORT }}"
  VELOTIMEDB_USERNAME: "{{ .Values.config.module_facilities_api.VELOTIMEDB_USERNAME }}"
  VELOTIMEDB_JDBCCONNECTIONSTRING: "{{ .Values.config.module_facilities_api.VELOTIMEDB_JDBCCONNECTIONSTRING }}"
  VELOTIMEDB_DATABASENAME: "{{ .Values.config.module_facilities_api.VELOTIMEDB_DATABASENAME }}"
