---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "module-facilities-api-deployment"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "module-facilities-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "velotime-apphost"
        app.kubernetes.io/component: "module-facilities-api"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.module_facilities_api.module_facilities_api_image }}"
          name: "module-facilities-api"
          envFrom:
            - configMapRef:
                name: "module-facilities-api-config"
            - secretRef:
                name: "module-facilities-api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.module_facilities_api.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.module_facilities_api.port_https }}"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "velotime-apphost"
      app.kubernetes.io/component: "module-facilities-api"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
