---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "module-statistics-migration-deployment"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "module-statistics-migration"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "velotime-apphost"
        app.kubernetes.io/component: "module-statistics-migration"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.module_statistics_migration.module_statistics_migration_image }}"
          name: "module-statistics-migration"
          envFrom:
            - configMapRef:
                name: "module-statistics-migration-config"
            - secretRef:
                name: "module-statistics-migration-secrets"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "velotime-apphost"
      app.kubernetes.io/component: "module-statistics-migration"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
