---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "frontend-config"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.frontend.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.frontend.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.frontend.HTTP_PORTS }}"
  CACHE_HOST: "{{ .Values.config.frontend.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.frontend.CACHE_PORT }}"
  KEYCLOAK_HTTP: "{{ .Values.config.frontend.KEYCLOAK_HTTP }}"
  services__keycloak__http__0: "{{ .Values.config.frontend.services__keycloak__http__0 }}"
  KEYCLOAK_MANAGEMENT: "{{ .Values.config.frontend.KEYCLOAK_MANAGEMENT }}"
  services__keycloak__management__0: "{{ .Values.config.frontend.services__keycloak__management__0 }}"
  MODULE_FACILITIES_API_HTTP: "{{ .Values.config.frontend.MODULE_FACILITIES_API_HTTP }}"
  services__module-facilities-api__http__0: "{{ .Values.config.frontend.services__module_facilities_api__http__0 }}"
  MODULE_FACILITIES_API_HTTPS: "{{ .Values.config.frontend.MODULE_FACILITIES_API_HTTPS }}"
  services__module-facilities-api__https__0: "{{ .Values.config.frontend.services__module_facilities_api__https__0 }}"
  MODULE_STATISTICS_API_HTTP: "{{ .Values.config.frontend.MODULE_STATISTICS_API_HTTP }}"
  services__module-statistics-api__http__0: "{{ .Values.config.frontend.services__module_statistics_api__http__0 }}"
  MODULE_STATISTICS_API_HTTPS: "{{ .Values.config.frontend.MODULE_STATISTICS_API_HTTPS }}"
  services__module-statistics-api__https__0: "{{ .Values.config.frontend.services__module_statistics_api__https__0 }}"
  MODULE_TIMING_API_HTTP: "{{ .Values.config.frontend.MODULE_TIMING_API_HTTP }}"
  services__module-timing-api__http__0: "{{ .Values.config.frontend.services__module_timing_api__http__0 }}"
  MODULE_TIMING_API_HTTPS: "{{ .Values.config.frontend.MODULE_TIMING_API_HTTPS }}"
  services__module-timing-api__https__0: "{{ .Values.config.frontend.services__module_timing_api__https__0 }}"
