---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "frontend-service"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.frontend.port_http }}"
      targetPort: "{{ .Values.parameters.frontend.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.frontend.port_https }}"
      targetPort: "{{ .Values.parameters.frontend.port_https }}"
