---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "module-statistics-processor-config"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "module-statistics-processor"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.module_statistics_processor.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.module_statistics_processor.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.module_statistics_processor.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  CACHE_HOST: "{{ .Values.config.module_statistics_processor.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.module_statistics_processor.CACHE_PORT }}"
  VELOTIMEDB_HOST: "{{ .Values.config.module_statistics_processor.VELOTIMEDB_HOST }}"
  VELOTIMEDB_PORT: "{{ .Values.config.module_statistics_processor.VELOTIMEDB_PORT }}"
  VELOTIMEDB_USERNAME: "{{ .Values.config.module_statistics_processor.VELOTIMEDB_USERNAME }}"
  VELOTIMEDB_JDBCCONNECTIONSTRING: "{{ .Values.config.module_statistics_processor.VELOTIMEDB_JDBCCONNECTIONSTRING }}"
  VELOTIMEDB_DATABASENAME: "{{ .Values.config.module_statistics_processor.VELOTIMEDB_DATABASENAME }}"
  MODULE_FACILITIES_API_HTTP: "{{ .Values.config.module_statistics_processor.MODULE_FACILITIES_API_HTTP }}"
  services__module-facilities-api__http__0: "{{ .Values.config.module_statistics_processor.services__module_facilities_api__http__0 }}"
  MODULE_FACILITIES_API_HTTPS: "{{ .Values.config.module_statistics_processor.MODULE_FACILITIES_API_HTTPS }}"
  services__module-facilities-api__https__0: "{{ .Values.config.module_statistics_processor.services__module_facilities_api__https__0 }}"
