---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "module-timing-api-config"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "module-timing-api"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.module_timing_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.module_timing_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.module_timing_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.module_timing_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.module_timing_api.HTTP_PORTS }}"
