---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "keycloak-config"
  labels:
    app.kubernetes.io/name: "velotime-apphost"
    app.kubernetes.io/component: "keycloak"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.config.keycloak.KC_BOOTSTRAP_ADMIN_USERNAME }}"
  KC_HEALTH_ENABLED: "{{ .Values.config.keycloak.KC_HEALTH_ENABLED }}"
  KC_FEATURES: "{{ .Values.config.keycloak.KC_FEATURES }}"
  KC_DB: "{{ .Values.config.keycloak.KC_DB }}"
  KC_DB_URL: "{{ .Values.config.keycloak.KC_DB_URL }}"
  KC_TRANSACTION_XA_ENABLED: "{{ .Values.config.keycloak.KC_TRANSACTION_XA_ENABLED }}"
  KC_DB_USERNAME: "{{ .Values.config.keycloak.KC_DB_USERNAME }}"
